#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[219] =
    {   0,
        0,    0,    0,    0,    0,    0,   67,   59,   56,   58,
       57,   59,    4,   59,   59,   59,   55,   51,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   66,   63,
       66,   61,   66,    0,   54,    0,    4,   65,   55,    0,
        0,    0,    0,    0,    0,    0,   46,   45,    0,    0,
        0,    3,    2,   53,    0,   52,   52,   52,   52,   52,
       26,   52,   52,   52,   52,   52,   52,   52,   52,   27,
       52,   52,   52,   52,   64,   62,   60,   53,    0,    0,
        0,    0,    0,    0,    0,   40,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   53,   53,

       53,   52,   21,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   22,   24,
       10,   52,   52,   52,   52,    0,    0,    0,    0,    0,
       39,    0,    0,    0,    0,   33,   43,    0,    0,   42,
        0,    0,    0,   44,    0,   41,   53,   53,   52,   52,
       52,   23,   11,   52,   28,   52,   52,   52,   52,   52,
       12,   52,   52,   52,   52,   52,   52,   52,   52,    0,
        0,    0,    0,   47,    0,   49,   48,   38,   35,   50,
       32,   36,   34,    0,   53,   53,   53,   30,   19,   29,
        7,   52,   13,   52,   25,   52,   52,   15,   17,    8,

       31,   52,   16,   18,   52,    0,    0,   53,   52,   14,
        5,   20,    6,   52,   37,    1,    9,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    1,    1,    1,
        1,    8,    1,    1,    9,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,   13,    1,
       14,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   16,   24,   25,   26,   27,   28,   29,
       16,   30,   31,   32,   33,   34,   35,   36,   37,   38,
        1,    1,    1,    1,   39,    1,   40,   16,   41,   42,

       43,   44,   45,   46,   47,   16,   48,   49,   50,   51,
       52,   53,   16,   54,   55,   56,   57,   58,   59,   60,
       61,   62,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   16,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   16,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   16,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    3,    4,    5,
        6,    4,    1,    1,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    4,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7
    } ;

static const flex_int16_t yy_base[236] =
    {   0,
        0,    0,  219,  181,   60,   61,  182, 1264, 1264, 1264,
     1264,   60,    0,  173,   60,   59,  142, 1264,   64,  109,
      117,  124,  113,  148,  192,  158,  169,  182,  132, 1264,
      130, 1264,   71,  123, 1264,  250,    0, 1264,   87,   67,
       58,   69,   73,   76,   90,  129,  170,  104,  118,  113,
      162, 1264, 1264,  226,   86,  233,  237,  257,  261,  309,
      265,  269,  293,  275,  301,  332,  317,  371,  337,  285,
      354,  420,  357,  386, 1264, 1264, 1264, 1264,  473,  512,
      133,  145,  276,  174,  161, 1264,  177,  183,  206,  250,
      253,  270,  281,  311,  313,   83,    0,   86,  396,  409,

      428,  414,  433,  498,  520,  526,  530,  451,  535,  545,
      561,  566,  586,  592,  598,  610,  617,  633,  488,  492,
      641,  648,  664,  669,  657,  724,  763,  134,    0,    0,
     1264,  313,  331,  328,  354, 1264, 1264,  366,  381, 1264,
      171,  398,  412, 1264,  401, 1264,  457,  680,  750,  702,
      771,  674,  739,  775,  743,  781,  785,  796,  807,  830,
      821,  835,  842,  858,  866,  877,  882,  889,  894,  213,
      951,  990, 1029, 1264,  402, 1264, 1264, 1264, 1264, 1264,
     1264, 1264, 1264,   67,  494,  541,  623,  903,  908,  927,
      936,  967,  971, 1013,  975, 1037, 1041, 1009, 1047, 1053,

     1061, 1065, 1069, 1078, 1084,    0,  445,  749, 1089, 1093,
     1097, 1106, 1110, 1115, 1264, 1121, 1130, 1264, 1171, 1178,
     1185, 1192, 1197, 1201, 1208, 1212, 1216, 1223, 1230,   59,
     1234, 1241, 1245, 1252, 1256
    } ;

static const flex_int16_t yy_def[236] =
    {   0,
      218,    1,  219,  219,  220,  220,  218,  218,  218,  218,
      218,  221,  222,  218,  218,  223,  218,  218,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  218,  218,
      218,  218,  218,  221,  218,  225,  222,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  226,  218,  227,  227,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,   68,  224,  218,  218,  218,  218,  228,  229,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  230,  223,  231,  226,

      231,  227,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  232,  229,  221,  127,  127,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  233,  231,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  221,
      234,  232,  234,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  235,  233,  235,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,

      224,  224,  224,  224,  224,  173,  218,  235,  224,  224,
      224,  224,  224,  224,  218,  224,  224,    0,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218
    } ;

static const flex_int16_t yy_nxt[1327] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,    8,   15,    8,
       16,   17,    8,   18,   19,   19,   20,   19,   21,   22,
       19,   19,   23,   19,   24,   25,   19,   19,   26,   27,
       19,   19,   28,   19,   19,   19,   19,   19,    8,   19,
       20,   19,   21,   22,   19,   19,   23,   19,   24,   25,
       19,   19,   26,   27,   19,   19,   28,   19,   19,   19,
       19,   19,   32,   32,   35,  147,   52,   33,   33,   53,
       36,   39,   55,   56,   40,   57,   41,   42,  185,   43,
       44,   77,   45,   76,   81,   82,   46,   83,   47,   48,
       49,   50,   51,  218,   99,   84,  218,   57,   39,   40,

       41,   42,   56,   43,   44,   85,   45,   86,   81,   82,
       46,   83,   47,   48,   49,   50,   51,   55,   56,   84,
       57,   55,   56,   59,   57,   55,   56,   35,   57,   85,
       60,   86,   55,   56,   62,   57,   90,   61,   35,   66,
       91,   64,   76,   87,   75,  129,   65,   56,   59,   92,
      131,   56,   63,   39,   60,   56,   55,   56,   62,   57,
       90,   61,   56,   66,   91,   64,   55,   56,   87,   57,
       65,  132,   71,   92,  131,   67,   63,   55,   56,   38,
       57,  218,   93,   30,   88,  180,   56,   72,   94,  137,
       55,   56,   95,   57,   73,  132,   56,   71,  135,   67,

       55,   56,  138,   57,   89,  136,   93,   56,   74,   88,
      180,   72,   94,  137,  139,   68,   95,   35,   73,   69,
       56,   30,  135,  140,  171,   70,  138,  218,   89,  136,
       56,  218,   74,  218,   96,   97,   98,   99,  139,   68,
      218,   55,   56,   69,   57,   55,   56,  140,   57,   70,
       34,   34,   34,   34,   78,   34,   34,   34,   34,   79,
       36,   34,   34,   34,  101,   55,   56,  218,   57,   55,
       56,   56,   57,   55,   56,   56,   57,   55,   56,  218,
       57,  141,  218,   55,   56,  218,   57,  218,   34,  218,
      142,  107,  103,   55,   56,   56,   57,  109,  143,   56,

      133,   55,   56,   56,   57,  141,  134,   56,  144,   55,
       56,  108,   57,   56,  142,  107,  103,   55,   56,  218,
       57,  109,  143,   56,  133,   55,   56,  110,   57,  104,
      134,   56,  144,  145,  105,  108,  106,  112,  218,   56,
       55,   56,  146,   57,  174,   55,   56,   56,   57,  175,
      218,  110,  218,  104,  111,   56,  218,  145,  105,  176,
      106,  112,   55,   56,  218,   57,  146,  218,  174,  117,
       56,  218,  177,  175,  122,   56,   58,  123,  111,   55,
       56,  218,   57,  176,  178,  218,  118,  218,  113,  124,
      114,  115,   56,  117,   55,   56,  177,   57,  122,  218,

       58,  123,  179,  116,   96,   97,   98,   99,  178,   56,
      118,  125,  113,  124,  114,  115,  181,   96,   97,   98,
       99,  218,   55,   56,   56,   57,  179,  116,   55,   56,
      182,   57,  183,  207,  101,  125,   96,   97,   98,   99,
      181,   55,   56,  218,   57,  119,  120,  101,  121,  218,
      218,  218,   56,  218,  182,  218,  183,  207,   56,   55,
       56,  218,   57,  215,  218,  184,  101,  153,  185,  119,
      120,   56,  121,   34,   34,   34,   34,   35,   34,   34,
       34,   34,   34,   34,   34,   34,   34,  215,  218,   56,
      218,  153,  218,  218,  218,  187,   55,   56,  218,   57,

       55,   56,  184,   57,  218,  185,   55,   56,  218,   57,
      218,   34,   34,   34,   34,  127,   35,   34,   34,   34,
      128,   34,   34,  129,   34,   34,   56,  149,   55,   56,
       56,   57,  187,  218,   55,   56,   56,   57,   55,   56,
      218,   57,  218,   55,   56,  218,   57,  150,  218,  184,
      127,  149,  185,   55,   56,  218,   57,  218,   56,  218,
      151,  152,  155,  218,   56,  154,  218,  218,   56,   55,
       56,  150,   57,   56,   55,   56,  218,   57,  218,  187,
      218,  218,  218,   56,  151,  152,  155,  218,  157,  154,
      218,  218,  156,  158,   55,   56,  218,   57,  218,   56,

       55,   56,  218,   57,   56,  218,   55,   56,  159,   57,
      218,  218,  157,  218,  160,  218,  156,  158,   55,   56,
      218,   57,  161,  218,   56,   55,   56,  162,   57,  218,
       56,  184,  159,  218,  185,  218,   56,  218,  160,  218,
      163,   55,   56,  164,   57,  218,  161,  218,   56,   55,
       56,  162,   57,  218,  218,   56,   55,   56,  218,   57,
      218,  187,  218,  165,  163,   55,   56,  164,   57,  218,
      166,   56,   55,   56,  218,   57,  218,   55,   56,   56,
       57,  218,   55,   56,  169,   57,   56,  165,   96,   97,
       98,   99,  218,  167,  166,   56,  218,  218,  218,  168,

      218,  218,   56,  218,  218,  218,  218,   56,  169,  218,
       55,   56,   56,   57,  218,  218,  218,  167,  101,  189,
      218,  218,  218,  168,   34,   34,   34,   34,   78,   34,
       34,   34,  170,   34,   34,  171,   34,   34,  218,  218,
       56,  218,  218,  189,  218,  218,  218,   55,   56,  218,
       57,   55,   56,  218,   57,  218,  218,  184,   55,   56,
      185,   57,  173,   34,   34,   34,  127,   78,   34,   34,
       34,  128,   79,   36,  129,   34,   34,   56,  188,   55,
       56,   56,   57,   55,   56,  218,   57,  187,   56,   55,
       56,  218,   57,   55,   56,  218,   57,  190,  191,  218,

      218,  127,  188,  192,   55,   56,  218,   57,  218,   56,
      218,  193,  218,   56,  218,   55,   56,  218,   57,   56,
      218,  190,  191,   56,  218,  218,  218,  192,  194,   55,
       56,  218,   57,  218,   56,  193,  195,  196,   55,   56,
      218,   57,  218,   55,   56,   56,   57,  218,  218,  218,
       55,   56,  194,   57,  197,  218,  218,  218,  218,   56,
      195,  196,  218,  198,  218,  218,   55,   56,   56,   57,
      218,  199,  218,   56,   55,   56,  218,   57,  197,  218,
       56,  218,  218,  218,  201,   55,   56,  198,   57,  200,
       55,   56,  218,   57,  218,  199,   56,   55,   56,  218,

       57,  218,   55,   56,   56,   57,  218,  202,  201,  218,
      203,   55,   56,  200,   57,   56,   55,   56,  204,   57,
       56,  218,  218,  218,  218,  218,  205,   56,  218,  218,
      218,  202,   56,  218,  203,   55,   56,  218,   57,  218,
      218,   56,  204,  218,   55,   56,   56,   57,  218,  218,
      205,   34,   34,   34,   34,   78,   34,   34,   34,  170,
       34,   34,  171,   34,   34,   56,  218,  218,  218,  218,
      218,  218,  218,  218,   56,   55,   56,  218,   57,   55,
       56,  209,   57,   55,   56,  218,   57,  218,  218,  173,
       34,   34,   34,   34,   78,   34,   34,   34,  170,   34,

       34,  171,   34,   34,  218,   56,  209,  218,  218,   56,
      218,  218,  218,   56,  218,  218,  218,   55,   56,  218,
       57,   55,   56,  218,   57,  218,  218,  218,  173,   34,
       34,   34,   34,   78,   34,   34,   34,  170,   34,   34,
      171,   34,   34,  218,  210,   55,   56,   56,   57,   55,
       56,   56,   57,  218,  218,   55,   56,  218,   57,  212,
      211,   55,   56,  218,   57,  218,  218,  173,  210,   55,
       56,  218,   57,   55,   56,   56,   57,   55,   56,   56,
       57,  218,  218,  212,  211,   56,   55,   56,  213,   57,
      218,   56,   55,   56,  218,   57,  218,   55,   56,   56,

       57,   55,   56,   56,   57,   55,   56,   56,   57,  218,
      214,  218,  213,  216,   55,   56,   56,   57,   55,   56,
      218,   57,   56,   55,   56,  218,   57,   56,  218,   55,
       56,   56,   57,  218,  214,   56,  218,  216,   55,   56,
      218,   57,  218,  218,   56,  218,  217,  218,   56,  218,
      218,  218,  218,   56,  218,  218,  218,  218,  218,   56,
      218,  218,  218,  218,  218,  218,  218,  218,   56,  218,
      217,   29,   29,   29,   29,   29,   29,   29,   31,   31,
       31,   31,   31,   31,   31,   34,   34,   34,   34,   34,
       34,   34,   37,  218,   37,   37,   37,   37,   37,   54,

      218,  218,   54,   54,   58,   58,  218,   58,   80,   80,
       80,   80,   80,   80,   80,  100,  100,  100,  100,  102,
      102,  218,  102,  126,  126,  126,  126,  126,  126,  126,
      130,  130,  130,  130,  130,  130,  130,  148,  148,  148,
      148,  172,  172,  172,  172,  172,  172,  172,  186,  218,
      218,  186,  206,  206,  206,  206,  206,  206,  206,  208,
      218,  218,  208,    7,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218
    } ;

static const flex_int16_t yy_chk[1327] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    6,   12,  230,   16,    5,    6,   16,
       12,   15,   19,   19,   15,   19,   15,   15,  184,   15,
       15,   33,   15,   33,   40,   41,   15,   42,   15,   15,
       15,   15,   15,   98,   96,   43,   98,   55,   39,   15,

       15,   15,   19,   15,   15,   44,   15,   45,   40,   41,
       15,   42,   15,   15,   15,   15,   15,   20,   20,   43,
       20,   23,   23,   20,   23,   21,   21,   34,   21,   44,
       20,   45,   22,   22,   21,   22,   48,   20,  128,   23,
       49,   22,   31,   46,   29,  128,   22,   20,   20,   50,
       81,   23,   21,   17,   20,   21,   24,   24,   21,   24,
       48,   20,   22,   23,   49,   22,   26,   26,   46,   26,
       22,   82,   26,   50,   81,   24,   21,   27,   27,   14,
       27,    7,   51,    4,   47,  141,   24,   27,   51,   85,
       28,   28,   51,   28,   27,   82,   26,   26,   84,   24,

       25,   25,   87,   25,   47,   84,   51,   27,   28,   47,
      141,   27,   51,   85,   88,   25,   51,  170,   27,   25,
       28,    3,   84,   89,  170,   25,   87,    0,   47,   84,
       25,    0,   28,    0,   54,   54,   54,   54,   88,   25,
        0,   56,   56,   25,   56,   57,   57,   89,   57,   25,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   54,   58,   58,    0,   58,   59,
       59,   56,   59,   61,   61,   57,   61,   62,   62,    0,
       62,   90,    0,   64,   64,    0,   64,    0,   36,    0,
       91,   62,   59,   70,   70,   58,   70,   64,   92,   59,

       83,   63,   63,   61,   63,   90,   83,   62,   93,   65,
       65,   63,   65,   64,   91,   62,   59,   60,   60,    0,
       60,   64,   92,   70,   83,   67,   67,   65,   67,   60,
       83,   63,   93,   94,   60,   63,   60,   67,    0,   65,
       66,   66,   95,   66,  132,   69,   69,   60,   69,  133,
        0,   65,    0,   60,   66,   67,    0,   94,   60,  134,
       60,   67,   71,   71,    0,   71,   95,    0,  132,   69,
       66,    0,  135,  133,   73,   69,   73,   73,   66,   68,
       68,    0,   68,  134,  138,    0,   71,    0,   68,   73,
       68,   68,   71,   69,   74,   74,  135,   74,   73,    0,

       73,   73,  139,   68,   99,   99,   99,   99,  138,   68,
       71,   74,   68,   73,   68,   68,  142,  100,  100,  100,
      100,    0,  102,  102,   74,  102,  139,   68,   72,   72,
      143,   72,  145,  175,   99,   74,  101,  101,  101,  101,
      142,  103,  103,    0,  103,   72,   72,  100,   72,    0,
        0,    0,  102,    0,  143,    0,  145,  175,   72,  108,
      108,    0,  108,  207,    0,  147,  101,  108,  147,   72,
       72,  103,   72,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,  207,    0,  108,
        0,  108,    0,    0,    0,  147,  119,  119,    0,  119,

      120,  120,  185,  120,    0,  185,  104,  104,    0,  104,
        0,   79,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,  119,  104,  105,  105,
      120,  105,  185,    0,  106,  106,  104,  106,  107,  107,
        0,  107,    0,  109,  109,    0,  109,  105,    0,  186,
       80,  104,  186,  110,  110,    0,  110,    0,  105,    0,
      106,  107,  110,    0,  106,  109,    0,    0,  107,  111,
      111,  105,  111,  109,  112,  112,    0,  112,    0,  186,
        0,    0,    0,  110,  106,  107,  110,    0,  112,  109,
        0,    0,  111,  112,  113,  113,    0,  113,    0,  111,

      114,  114,    0,  114,  112,    0,  115,  115,  113,  115,
        0,    0,  112,    0,  114,    0,  111,  112,  116,  116,
        0,  116,  114,    0,  113,  117,  117,  115,  117,    0,
      114,  187,  113,    0,  187,    0,  115,    0,  114,    0,
      116,  118,  118,  117,  118,    0,  114,    0,  116,  121,
      121,  115,  121,    0,    0,  117,  122,  122,    0,  122,
        0,  187,    0,  118,  116,  125,  125,  117,  125,    0,
      122,  118,  123,  123,    0,  123,    0,  124,  124,  121,
      124,    0,  152,  152,  125,  152,  122,  118,  148,  148,
      148,  148,    0,  123,  122,  125,    0,    0,    0,  124,

        0,    0,  123,    0,    0,    0,    0,  124,  125,    0,
      150,  150,  152,  150,    0,    0,    0,  123,  148,  150,
        0,    0,    0,  124,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,    0,    0,
      150,    0,    0,  150,    0,    0,    0,  153,  153,    0,
      153,  155,  155,    0,  155,    0,    0,  208,  149,  149,
      208,  149,  126,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  127,  127,  127,  127,  153,  149,  151,
      151,  155,  151,  154,  154,    0,  154,  208,  149,  156,
      156,    0,  156,  157,  157,    0,  157,  151,  154,    0,

        0,  127,  149,  156,  158,  158,    0,  158,    0,  151,
        0,  157,    0,  154,    0,  159,  159,    0,  159,  156,
        0,  151,  154,  157,    0,    0,    0,  156,  158,  161,
      161,    0,  161,    0,  158,  157,  159,  159,  160,  160,
        0,  160,    0,  162,  162,  159,  162,    0,    0,    0,
      163,  163,  158,  163,  160,    0,    0,    0,    0,  161,
      159,  159,    0,  162,    0,    0,  164,  164,  160,  164,
        0,  163,    0,  162,  165,  165,    0,  165,  160,    0,
      163,    0,    0,    0,  165,  166,  166,  162,  166,  164,
      167,  167,    0,  167,    0,  163,  164,  168,  168,    0,

      168,    0,  169,  169,  165,  169,    0,  166,  165,    0,
      167,  188,  188,  164,  188,  166,  189,  189,  168,  189,
      167,    0,    0,    0,    0,    0,  169,  168,    0,    0,
        0,  166,  169,    0,  167,  190,  190,    0,  190,    0,
        0,  188,  168,    0,  191,  191,  189,  191,    0,    0,
      169,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  190,    0,    0,    0,    0,
        0,    0,    0,    0,  191,  192,  192,    0,  192,  193,
      193,  192,  193,  195,  195,    0,  195,    0,    0,  171,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,

      172,  172,  172,  172,    0,  192,  192,    0,    0,  193,
        0,    0,    0,  195,    0,    0,    0,  198,  198,    0,
      198,  194,  194,    0,  194,    0,    0,    0,  172,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  173,  173,    0,  194,  196,  196,  198,  196,  197,
      197,  194,  197,    0,    0,  199,  199,    0,  199,  197,
      196,  200,  200,    0,  200,    0,    0,  173,  194,  201,
      201,    0,  201,  202,  202,  196,  202,  203,  203,  197,
      203,    0,    0,  197,  196,  199,  204,  204,  202,  204,
        0,  200,  205,  205,    0,  205,    0,  209,  209,  201,

      209,  210,  210,  202,  210,  211,  211,  203,  211,    0,
      205,    0,  202,  209,  212,  212,  204,  212,  213,  213,
        0,  213,  205,  214,  214,    0,  214,  209,    0,  216,
      216,  210,  216,    0,  205,  211,    0,  209,  217,  217,
        0,  217,    0,    0,  212,    0,  214,    0,  213,    0,
        0,    0,    0,  214,    0,    0,    0,    0,    0,  216,
        0,    0,    0,    0,    0,    0,    0,    0,  217,    0,
      214,  219,  219,  219,  219,  219,  219,  219,  220,  220,
      220,  220,  220,  220,  220,  221,  221,  221,  221,  221,
      221,  221,  222,    0,  222,  222,  222,  222,  222,  223,

        0,    0,  223,  223,  224,  224,    0,  224,  225,  225,
      225,  225,  225,  225,  225,  226,  226,  226,  226,  227,
      227,    0,  227,  228,  228,  228,  228,  228,  228,  228,
      229,  229,  229,  229,  229,  229,  229,  231,  231,  231,
      231,  232,  232,  232,  232,  232,  232,  232,  233,    0,
        0,  233,  234,  234,  234,  234,  234,  234,  234,  235,
        0,    0,  235,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[67] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 
    0, 1, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 4 "lex.l"
#include <cstdlib>
#include "parser.h"
#include <QString>
#include <stdio.h>
#include <iostream>
#include <iostream>
int yylex();
void yyerror(const char *s);

int linea=0;
int columna = 1;

#line 852 "scanner.cpp"

#line 854 "scanner.cpp"

#define INITIAL 0
#define COM 1
#define COMM 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 34 "lex.l"

#line 1073 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 219 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1264 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "lex.l"

	YY_BREAK

case 2:
YY_RULE_SETUP
#line 37 "lex.l"
{  BEGIN COM; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "lex.l"
{  BEGIN COMM; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "lex.l"
{ /*Se ignoran*/ std::cout << yytext << std::endl;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_MKDISK;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_RMDISK;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_FDISK;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_MOUNT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_UNMOUNT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_REP;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_EXEC;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_MKFS;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_LOGIN;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_LOGOUT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_MKGRP;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_RMGRP;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_MKUSR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_RMUSR;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_CHMOD;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_MKFILE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_CAT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_REM;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_EDIT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_REN;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_MKDIR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_CP;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_MV;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_FIND;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_CHOWN;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_CHGRP;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_PAUSE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 76 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_SIZE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 77 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_FIT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 78 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_UNIT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 79 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_PATH;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 80 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_TYPE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 81 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_DELETE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 82 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_NAME;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 83 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_ADD;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 84 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_ID;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 87 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_USR;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 88 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_PWD;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 89 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_GRP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 90 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_UGO;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 91 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_R;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 92 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_P;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 93 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_CONT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 94 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_FILE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 95 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_DEST;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 96 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_PARM_RUTA;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 101 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_EQUALS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 102 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_IDENT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 103 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_RUTA;}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 104 "lex.l"
{strcpy(yylval.TEXT, yytext); return TK_CADENA;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 108 "lex.l"
{  strcpy(yylval.TEXT, yytext); return TK_NUMBER;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 111 "lex.l"
{
                    strcpy(yylval.TEXT, yytext);
            }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 114 "lex.l"

	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 115 "lex.l"

	YY_BREAK
case 59:
YY_RULE_SETUP
#line 116 "lex.l"
{
                    strcpy(yylval.TEXT, yytext);
            }
	YY_BREAK

case 60:
YY_RULE_SETUP
#line 120 "lex.l"
{ BEGIN INITIAL; }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 121 "lex.l"
{linea++;};
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 122 "lex.l"

	YY_BREAK
case YY_STATE_EOF(COMM):
#line 123 "lex.l"
{ yyerror("unclosed comment"); }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 124 "lex.l"
{ linea++; columna = 0; BEGIN INITIAL; };
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 125 "lex.l"

	YY_BREAK
case 65:
YY_RULE_SETUP
#line 126 "lex.l"

	YY_BREAK
case 66:
YY_RULE_SETUP
#line 127 "lex.l"
ECHO;
	YY_BREAK
#line 1484 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COM):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 219 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 219 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 218);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 127 "lex.l"
